stages:
  - build

build-package:
  stage: build
  image: docker/compose:latest
  script:
    - DATA=$(date +'%Y%m%d%H%M%S')
    - docker login redeslab.info.ufrn.br:5050 -u $CI_USER_TESTE -p $CI_TESTE_TOKEN
    - docker build -t redeslab.info.ufrn.br:5050/teste/autoticket:v$DATA .
    - docker push redeslab.info.ufrn.br:5050/teste/autoticket:v$DATA

  rules:
    - if: ($CI_COMMIT_BRANCH ==  $CI_DEFAULT_BRANCH)
