# Generated by Django 4.0.5 on 2022-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Name')),
                ('descricao', models.TextField(max_length=255, null=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('Emergencial', 1), ('Urgente', 2), ('Alta', 3), ('Media', 4), ('Baixa', 5)], default='Media', max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(null=True)),
            ],
        ),
    ]
