# Generated by Django 4.0.5 on 2022-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
