# Generated by Django 4.0.5 on 2022-10-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoticketapp', '0004_alter_group_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='autoticketapp.group'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridade',
            field=models.CharField(choices=[(1, 'Emergencial'), (2, 'Urgente'), (3, 'Alta'), (4, 'Media'), (5, 'Baixa')], default=4, max_length=50),
        ),
    ]
