# Generated by Django 4.0.5 on 2022-10-01 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoticketapp', '0006_alter_service_status_alter_ticket_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='service',
            field=models.ManyToManyField(related_name='templates', to='autoticketapp.service'),
        ),
        migrations.CreateModel(
            name='provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provision_template', to='autoticketapp.ticket')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provision_ticket', to='autoticketapp.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
