# Generated by Django 4.2 on 2023-04-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('value', models.TextField(verbose_name='value')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryParameters', to='iac.typeinput')),
            ],
        ),
    ]
