# Generated by Django 4.2 on 2023-04-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0003_playbookparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ansible_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('collection', models.CharField(blank=True, max_length=200, verbose_name='collection')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ansible_module_variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('variable_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='type')),
                ('choices', models.CharField(blank=True, max_length=255, null=True, verbose_name='choices')),
                ('required', models.BooleanField(default=False)),
                ('module_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ansible_modules', to='iac.ansible_module')),
            ],
        ),
    ]
