# Generated by Django 4.2 on 2023-04-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0004_ansible_module_ansible_module_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansible_module_variable',
            old_name='module_id',
            new_name='module',
        ),
    ]
