# Generated by Django 4.2 on 2023-04-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0005_rename_module_id_ansible_module_variable_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ansible_module',
            new_name='AnsibleModule',
        ),
        migrations.RenameModel(
            old_name='ansible_module_variable',
            new_name='AnsibleModuleVariable',
        ),
    ]
